import {useState} from 'react';
import Cadastro from './Cadastro';
import type {Registro} from '../src/banco';
import {api} from './api';
export default function Agendamento(){
 const [periodo,setPeriodo]=useState('Semana');const [dia,setDia]=useState(new Date().toLocaleDateString('en-CA'));const [repeticao,setRepeticao]=useState<Registro|null>(null);const [quantidade,setQuantidade]=useState(4);
 const [aula,setAula]=useState<Registro|null>(null);const [data,setData]=useState('');const [hora,setHora]=useState('');const [erro,setErro]=useState('');
 async function reagendar(){if(!aula)return;try{await api('/aulas/'+aula.id+'/reagendar','POST',{data,hora,versao:aula.versao});setAula(null);window.dispatchEvent(new Event('cadastro-atualizado'));}catch(e){setErro((e as Error).message);}}
 return <><h2>Agenda</h2><Cadastro titulo="Aulas" tipo="aulas" campos={[
 {nome:'alunoId',rotulo:'Aluno',fonte:'alunos'},{nome:'data',rotulo:'Data',tipo:'data'},{nome:'hora',rotulo:'Horário',tipo:'hora'},{nome:'duracaoMinutos',rotulo:'Duração (minutos)',tipo:'numero',minimo:15,inicial:60},
 {nome:'status',rotulo:'Situação',opcoes:['Agendada','Realizada','Falta','Falta justificada','Falta do professor','Cancelada pelo aluno','Cancelada pelo professor','Reagendada','Reposição realizada']},
 {nome:'justificativa',rotulo:'Justificativa da falta',tipo:'area',opcional:true},{nome:'pacoteId',rotulo:'Pacote (opcional)',fonte:'pacotes',opcional:true},{nome:'originalId',rotulo:'Aula original da reposição',fonte:'aulas',opcional:true},{nome:'link',rotulo:'Link da videochamada',opcional:true},{nome:'conteudos',rotulo:'Conteúdo da aula',tipo:'area',opcional:true}
 ]} rodape={(aulas,refs)=>{const inicio=new Date(dia+'T12:00:00');const fim=new Date(inicio);if(periodo==='Semana'){inicio.setDate(inicio.getDate()-inicio.getDay());fim.setTime(inicio.getTime());fim.setDate(fim.getDate()+6);}if(periodo==='Mês'){inicio.setDate(1);fim.setMonth(fim.getMonth()+1,0);}const lista=aulas.filter(a=>{const data=new Date(String(a.dados.data)+'T12:00:00');return data>=inicio&&data<=fim;}).sort((a,b)=>(String(a.dados.data)+a.dados.hora).localeCompare(String(b.dados.data)+b.dados.hora));return <section className="cadastro"><h3>Agenda por período</h3><div className="filtros"><label>Visualização<select value={periodo} onChange={e=>setPeriodo(e.target.value)}><option>Dia</option><option>Semana</option><option>Mês</option></select></label><label>Data de referência<input type="date" required value={dia} onChange={e=>{if(e.target.value)setDia(e.target.value);}}/></label></div>{lista.map(a=><p key={a.id}>{String(a.dados.data)} às {String(a.dados.hora)} — {refs.alunos?.find(s=>s.id===a.dados.alunoId)?.nome} — {String(a.dados.status)}</p>)}{!lista.length&&<p>Nenhuma aula neste período.</p>}</section>;}} acoes={r=>r.dados.status==='Agendada'&&<><button onClick={()=>{setRepeticao(r);setErro('');}}>Repetir semanalmente</button><button onClick={()=>{setAula(r);setData(String(r.dados.data));setHora(String(r.dados.hora));setErro('');}}>Reagendar</button></>}/>{repeticao&&<section className="cadastro"><h3>Repetir aula semanalmente</h3><p>As novas aulas terão o mesmo aluno, horário e pacote. Se houver conflito ou falta de saldo, nenhuma repetição será criada.</p>{erro&&<p role="alert">{erro}</p>}<form onSubmit={async e=>{e.preventDefault();try{await api('/aulas/'+repeticao.id+'/repetir','POST',{quantidade});setRepeticao(null);window.dispatchEvent(new Event('cadastro-atualizado'));}catch(e){setErro((e as Error).message);}}}><label>Quantidade de novas aulas<input type="number" min="1" max="52" step="1" required value={quantidade} onChange={e=>setQuantidade(Number(e.target.value))}/></label><button type="submit">Criar repetições</button> <button type="button" onClick={()=>setRepeticao(null)}>Cancelar</button></form></section>}{aula&&<section className="cadastro"><h3>Reagendar aula</h3><p>A aula original ficará no histórico.</p>{erro&&<p role="alert">{erro}</p>}<form onSubmit={e=>{e.preventDefault();void reagendar();}}><div className="campos"><label>Nova data<input type="date" required value={data} onChange={e=>setData(e.target.value)}/></label><label>Novo horário<input type="time" required value={hora} onChange={e=>setHora(e.target.value)}/></label></div><button type="submit">Salvar reagendamento</button> <button type="button" onClick={()=>setAula(null)}>Cancelar</button></form></section>}</>;
}
